import { useEffect } from "react";
import Header from "./Header/Header";
import Footer from "./Footer/Footer";
import type { AppProps } from "next/app";
import Modal from "../Modal/Modal";
import { DynaPuff } from "next/font/google";
import Head from "next/head";

const dynaPuff = DynaPuff({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-dynaPuff',
})

interface Props {
    children: JSX.Element | JSX.Element[];
}

const Layout = ({ children }: Props) => {
    return (
        <div className={`${dynaPuff.variable}`}>
            <Head>
                <title>Fashion Shop</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <Modal />
            <div className="min-h-[64vh]">
                {children}
            </div>
            <Footer />
        </div>
    )
}


export default Layout;